/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/unyt/array.py:1778: RuntimeWarning: invalid value encountered in true_divide
  out_arr = func(
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/unyt/array.py:1778: RuntimeWarning: invalid value encountered in true_divide
  out_arr = func(
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/unyt/array.py:1778: RuntimeWarning: invalid value encountered in true_divide
  out_arr = func(
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/unyt/array.py:1778: RuntimeWarning: invalid value encountered in true_divide
  out_arr = func(
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/unyt/array.py:1778: RuntimeWarning: invalid value encountered in true_divide
  out_arr = func(
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/unyt/array.py:1778: RuntimeWarning: invalid value encountered in true_divide
  out_arr = func(
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_lookback_time (vectorized)
  outputs = ufunc(*inputs)
/cosma/local/Python/3.10.1/lib/python3.10/site-packages/unyt/array.py:1778: RuntimeWarning: invalid value encountered in true_divide
  out_arr = func(
